---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    workflow_exports:
      - name: INFRASTRUCTURE / New Edge server
        filename: workflow-new-edge-server.yml
      - name: DEV / Release Application Version
        filename: workflow-release-application.yml

  tasks:
    - name: Export workflow job template
      ansible.controller.export:
        workflow_job_templates: "{{ item.name }}"
      register: export_results
      loop: "{{ workflow_exports }}"

    - name: Export workflow job template to file
      ansible.builtin.copy:
        content: "{{ item.assets | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: "{{ item.item.filename }}"
      loop: "{{ export_results.results }}"
