---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: false
 
  tasks:
    - name: Export workflow job template
      ansible.controller.export:
        workflow_job_templates: APP / Rollout Edge Application
      register: export_results

    - debug:
        var: export_results

    - name: Export workflow job template to file
      copy:
        content: "{{ export_results | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: workflow.yaml
