---
- name: Configure demo ansible Controller 
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - vars/workflow-job-templates.yml
  vars:
    inventory_groups:
      - name: dev
        hosts:
          - node1
        variables: 
          environment_name: dev
          application_version: 0.0.2
      - name: prod
        hosts:
          - node2
          - node3
        variables: 
          environment_name: prod
          application_version: 0.0.1
      - name: edge-all
        variables:
          edge_app_service_name: edge-application
        children:
          - dev
          - prod
    job_templates:
      - name: INFRASTRUCTURE / Server Base Setup
        playbook: server-base.yml
        limit: edge-all
        ask_limit_on_launch: true
      - name: INFRASTRUCTURE / Podman Setup
        playbook: podman-setup.yml
        limit: edge-all
        ask_limit_on_launch: true
      - name: DEV / Podman App Deploy
        playbook: podman-app.yml
        limit: edge-all
        survey: templates/podman-app-deploy-survey.json
      - name: DEV / Smoke Test App
        playbook: smoke-test-app.yml
        limit: edge-all
        survey: templates/smoke-test-survey.json
      - name: DEV / Set Application Version
        playbook: set-version.yml
        survey_spec_file: templates/set-version-survey.json
        credential: Controller Credential
      - name: MAINTENANCE / Restart Application
        playbook: restart-application.yml
        limit: edge-all
        ask_limit_on_launch: true

  tasks:
    - name: Configure Ansible Controller Demo Project
      ansible.controller.project:
        name: Demo app
        organization: "Default"
        state: present
        update_project: true
        scm_update_on_launch: true
        scm_type: git
        scm_url: https://github.com/jwerak/ed-ansible-project.git
        scm_branch: main

    - name: Configure Inventory groups
      ansible.controller.group:
        name: "{{ item.name }}"
        inventory: Workshop Inventory
        hosts: "{{ item.hosts | default(omit) }}"
        variables: "{{ item.variables | default(omit) }}"
        children: "{{ item.children | default(omit) }}"
      loop: "{{ inventory_groups | default(omit) }}"

    - name: Configure Ansible Controller Job Templates
      ansible.controller.job_template:
        name: "{{ item.name }}"
        inventory: Workshop Inventory
        project: Demo app
        playbook: "{{ item.playbook }}"
        credential: "{{ item.credential | default('Workshop Credential') }}"
        ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(omit) }}"
        limit: "{{ item.limit | default(omit) }}"
        survey_spec: "{{ lookup('file', item.survey_spec_file  | default(omit), errors='ignore') | default(omit, true) }}"
        survey_enabled: true
      loop: "{{ job_templates }}"

    # - name: Configure Workflow Job Template
    #   ansible.controller.workflow_job_template:
    #     name: "{{ __workflow_loop_item.name }}"
    #     schema: "{{ __workflow_loop_item.related.workflow_nodes }}"
    #     limit: edge-all
    #     ask_limit_on_launch: true
    #   loop: "{{ workflow_job_templates }}"
    #   loop_control:
    #     loop_var: __workflow_loop_item
    
    - name: Configure Workflow Job Templates
      ansible.controller.workflow_job_template:
        name: "{{ __workflow_loop_item.name }}"
        schema: "{{  __workflow_loop_item.related.workflow_nodes }}"
        limit: "{{  __workflow_loop_item.limit }}"
        ask_limit_on_launch: "{{  __workflow_loop_item.ask_limit_on_launch }}"
        survey_enabled: "{{  __workflow_loop_item.survey_enabled }}"
        survey_spec: "{{  __workflow_loop_item.related.survey_spec }}"
      loop: "{{ workflow_job_templates }}"
      loop_control:
        loop_var: __workflow_loop_item